### PR TITLE
storage: Fix read all content at once when readdir

### LINKED ISSUE #16: ReadDir by offset instead read all content at once
When the Dir is large, reading it all at once is not a good solution.
We should add new functions to read by offset like other services.

### PR DESCRIPTION
**Pull request by bokket**
Signed-off-by: bokket <3100563328@qq.com>
fix: #16

### CODE REVIEW

File: readdir.go [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+}
+
+func (i *listDirInput) ContinuationToken() string {
+	return i.continuationToken
+}
+
+func (s *Storage) listDirNext(ctx context.Context, page *types.ObjectPage) (err error) {
+	input := page.Status.(*listDirInput)
+
+	input.fileList, err = s.hdfs.ReadDir(input.rp)
```
Comment (Xuanwo) [inline readdir.go]: `s.hdfs.ReadDir(input.rp)` always read all content at once, see code here: https://github.com/colinmarc/hdfs/blob/master/readdir.go

```go
func (c *Client) ReadDir(dirname string) ([]os.FileInfo, error) {
	f, err := c.Open(dirname)
	if err != nil {
		return nil, err
	}

	return f.Readdir(0)
}
```

Instead, we need to open the dir and read them via count.

And we don't need to store fileList/counter in `listDirInput`.

Comment (bokket) [reply readdir.go]: So count is up to us? For example `const defaultListObjectCount=100`
Otherwise, we still need to readDir to get the slice and calculate the count

Comment (Xuanwo) [reply readdir.go]: What we need is `limit` instead of `count`, there is no need for `list` to calculate the count.

We only need to `f.Readdir(limit)` and return `IteratorDone` if we meet `io.EOF`.

Ref: https://github.com/colinmarc/hdfs/blob/master/file_reader.go#L255-L257

Comment (bokket) [reply readdir.go]: Yes, this is slightly confusing, and I thought of using a constant to represent the read upper limit? Maybe there is something wrong with my description

File: readdir.go [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+
+func (s *Storage) listDirNext(ctx context.Context, page *types.ObjectPage) (err error) {
+	input := page.Status.(*listDirInput)
+
+	dir, err := s.hdfs.Open(input.rp)
+	if err != nil {
+		return err
+	}
+
+	for {
```
Comment (Xuanwo) [inline readdir.go]: Please don't use `for` in `listDirNext`. 

Our iterator will do this job: 
https://github.com/beyondstorage/go-storage/blob/de387baae5e6b246358c10ce01e333fb2d5f454b/types/iterator.generated.go#L125-L154

Our iterator provides `Next()` for users to call. And it will call `listDirNext` internally when all data has been consumed, so we don't need to do a loop by ourselves.

- Read `limit` files and update `page.Data`.
- Return `IterateDone` if there are no more files.

File: readdir.go [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+}
+
+func (i *listDirInput) ContinuationToken() string {
+	return i.continuationToken
+}
+
+func (s *Storage) listDirNext(ctx context.Context, page *types.ObjectPage) (err error) {
+	input := page.Status.(*listDirInput)
+
+	dir, err := s.hdfs.Open(input.rp)
```
Comment (Xuanwo) [inline readdir.go]: Maybe we need to store `dir` in `page.Status`?

- If we open dir every time in `listDirNext`, we can only list first 100 files.
- We can close `dir` before returning `IterateDone`

Comment (bokket) [reply readdir.go]: - If we open dir every time in listDirNext, we can only list first 100 files.

Maybe we could increase the limit each time until we reach `EOF `? but that would repeat the read of the previous file.
So maybe we could probably use a slicing process to weed out the files before 100 each time. Do you think it would ok?

File: readdir.go [hunk 4]
```diff
@@ -23,18 +25,18 @@ func (i *listDirInput) ContinuationToken() string {
...
 	}
 
-	defer func() {
-		dir.Close()
-	}()
-
-	fileList, err := dir.Readdir(defaultListObjectLimit)
+	fileList, err := input.dir.Readdir(defaultListObjectLimit)
 
 	if err != nil && err == io.EOF {
```
Comment (JinnyYi) [inline readdir.go]: Maybe we should use errors.Is to assert error's type?

File: readdir.go [hunk 5]
```diff
@@ -0,0 +1,63 @@
+package hdfs
+
+import (
+	"context"
+	"io"
+
+	"github.com/beyondstorage/go-storage/v4/types"
+
```
Comment (Prnyself) [inline readdir.go]: remove the blank line

File: storage.go [hunk 6]
```diff
@@ -143,6 +126,11 @@ func (s *Storage) move(ctx context.Context, src string, dst string, opt pairStor
 func (s *Storage) read(ctx context.Context, path string, w io.Writer, opt pairStorageRead) (n int64, err error) {
 	rp := s.getAbsPath(path)
 	f, err := s.hdfs.Open(rp)
+
+	defer func() {
+		err = f.Close()
```
Comment (Prnyself) [inline storage.go]: We should add nil check for `err` before assign `f.Close()` to it.

In this way, the real `err` may be covered by `f.Close()`

Comment (Prnyself) [reply storage.go]: take https://github.com/beyondstorage/go-service-ftp/blob/master/storage.go#L111 as a reference

**Review by JinnyYi — APPROVED** [review]
